pluginManagement {
    plugins {
        id 'org.springframework.boot' version "${springBootVersion}"
        id 'io.spring.dependency-management' version "${springDependencyManagementVersion}"
        id 'org.asciidoctor.jvm.convert' version "${asciidoctorConvertVersion}"
        id 'io.spring.javaformat' version "${springJavaFormatVersion}"
    }
}

rootProject.name = 'spring-boot-java-template'

include 'soo-core:core-enum'
include 'soo-core:core-api'
include 'soo-core:core-auth'
include 'soo-storage:db-core'
include 'soo-tests:api-docs'
include 'soo-support:logging'
include 'soo-support:monitoring'
include 'soo-clients:client-login-kakao'
